global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'inferenceHelperServiceLocal'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.22.174.171:8501']
  - job_name: 'inferenceHelperServiceEdge'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '172.22.174.171:8701' ]
  - job_name: 'inferenceHelperServiceCloud'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '172.22.174.171:8901' ]
  - job_name: 'kube-state-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.22.174.171:32000']
  - job_name: 'kepler-metrics'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '172.22.174.171:32602' ]
  - job_name: 'kube-state-metrics-edge'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.22.174.220:32000']
  - job_name: 'kepler-metrics-edge'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '172.22.174.220:32602' ]
