global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'inferenceHelperServiceLocal'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus' 
    static_configs:
      - targets: ['172.22.174.240:8501']
  - job_name: 'inferenceHelperServiceEdge'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '172.22.174.240:8701' ]
  - job_name: 'inferenceHelperServiceCloud'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '172.22.174.240:8901' ]
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: [ '172.22.174.240:8080' ]