scrape_configs:
  - job_name: 'inferenceService'
    metrics_path: '/actuator/prometheus' 
    static_configs:
      - targets: ['localhost:8501']
  - job_name: 'k6LoadTesting'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:6565'] 